"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
##############################################
##djago defult
from pathlib import Path
##############################################
import os
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")
##############################################
## deep pakages
import tensorflow as tf
import keras
##############################################
from FarhadCV.Tools import tcolors, bcolors
##############################################
## Load encoder:
## TFLite format:
# from Tools_Stega.tools_TFLite import TFLite_Encoder_Loader
# from Tools_Stega.tools_TFLite_decoder import TFLite_Decoder_Loader
## ckpt format:
# from Tools_Stega.Tools_tensorflow import TF2_Encoder_Loader
# from Tools_Stega.Tools_tensorflow_decoder import TF2_Decoder_Loader

##############################################
from DetectionLibs.main import Detection_Models
##############################################
## my pakage
##############################################
print(tcolors.RED+bcolors.BLACK,"Keras-Version:", keras.__version__, tcolors.ENDC)
print(tcolors.RED+bcolors.BLACK,"Tensorflow-Version:", tf.__version__, tcolors.ENDC)


#######################################################
######        Load TFLite StampOne Router         ######
#######################################################
 ## name model this file should write with big alphabets
## Load Encoder;
# encoder_model_path = f"./Tools_Stega/TFLite_models/24_11_4_AttentionVNet_RUE089/Encoder_24_11_4_AttentionVNet_RUE089_160.tflite"
# STAMPONE_ENCODER = TFLite_Encoder_Loader(args, path_encoder=encoder_model_path, secret_size=256, batch_size=1)
#######################################################
## Load TFLITE Decoder;
# from Tools_Stega.tools_TFLite_decoder import TFLite_Decoder_Loader
# decoder_model_path = (f"./Tools_Stega/TFLite_models/24_11_4_AttentionVNet_RUE089/"+
#                       "Decoder_24_11_4_AttentionVNet_RUE089_160.tflite")
# STAMPONE_DECODER = TFLite_Decoder_Loader(path_decoder=decoder_model_path, secret_size=256)
# print(tcolors.GREEN, 'STAMPOEN_DECODER is Loded successfully', tcolors.ENDC)




#######################################################
######        Load TF StampOne Router         ######
#######################################################
# from Tools_Stega.Tools_tensorflow_decoder import TF2_Decoder_Loader
# decoder_checkpoint_path = "./Tools_Stega/Models/StampOne_v89/" + "StampOne_decoder_v89_weights.weights.h5"
# STAMPONE_DECODER = TF2_Decoder_Loader(args=None, shape_message=(16,16), 
#                                      batch_size=1, path=decoder_checkpoint_path)
#######################################################
######        Load Keras StampOne Router         ######
#######################################################
# from Tools_Stega2.Tools_tensorflow_decoder import TF2_Decoder_Loader
# decoder_checkpoint_path = ("./Tools_Stega/Models/" + 
#                            "24_11_4_AttentionVNet_Conv1dDenseGate_M1616_sirin_RUE089/"+
#                            "Decoder_"+"24_11_4_AttentionVNet_Conv1dDenseGate_M1616_sirin_RUE089"+
#                            "_160000.ckpt")
# STAMPONE_DECODER = TF2_Decoder_Loader(args=None, shape_message=(16,16), 
#                                      batch_size=1, path=decoder_checkpoint_path)

#######################################################
######        Load TFLite StampOne Router         ######
#######################################################
with tf.device("gpu:1"):
    from Tools_stega89_de1.tools_TFLite_decoder import TFLite_Decoder_Loader
    STAMPONE_DECODER  = TFLite_Decoder_Loader()


#######################################################
######        Load Detection Router         ######
#######################################################
with tf.device("gpu:1"):
    DETECT_ROUTER = Detection_Models()

#######################################################
######                 Django Setting            ######
#######################################################
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment (or a local .env file) for real deployments.
# The fallback below is only for local development.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-0qsnv#)f6&j2y2zo!gzzdrl%nb1ksaa)19ki4u)-_mv9j=e9$d",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#######################################################
######          STATIC-IMAGE                     ######
#######################################################
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

#######################################################
######                                       ######
#######################################################
## Setup media path
MEDIA_URL = "/media/Encoded_images/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/Encoded_images')

IMAGES_URL = "/Images/"
IMAGES_ROOT = os.path.join(BASE_DIR, 'Images')

ENC_URL = "/media/Encoded_images/"
FACE_URL = "/media/Encoded_faces/"

ENC_ROOT = os.path.join(BASE_DIR, 'media/Encoded_images')
FACE_ROOT = os.path.join(BASE_DIR, 'media/Encoded_faces')



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'